CREATE TABLE PUBLIC."USER"
(ID VARCHAR(50) NOT NULL,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
CREATED VARCHAR(30) NOT NULL,
MODIFIED VARCHAR(30) NOT NULL,
LAST_LOGIN VARCHAR(30), 
TOKEN VARCHAR(50),
PRIMARY KEY (ID));

CREATE TABLE PUBLIC."PHONE"
(ID INTEGER IDENTITY PRIMARY KEY,
USER_ID VARCHAR(50) NOT NULL,
NUMBER INTEGER NOT NULL,
DDD INTEGER NOT NULL);